# Generated by Django 5.1.1 on 2024-09-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='city',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='email',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='record',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='record',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='state',
        ),
        migrations.RemoveField(
            model_name='record',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='record',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='record',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.TextField(),
        ),
    ]
